//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.17929
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu.WS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IdmServerbinding", Namespace="http://tempuri.org/")]
    public partial class IdmServerservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public IdmServerservice() {
            this.Url = "";
        }
        
        public IdmServerservice(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#SAS_ApplyUpdates", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("ErrorCount")]
        public int SAS_ApplyUpdates(string ProviderName, object Delta, int MaxErrors, ref object OwnerData, out object @return) {
            object[] results = this.Invoke("SAS_ApplyUpdates", new object[] {
                        ProviderName,
                        Delta,
                        MaxErrors,
                        OwnerData});
            OwnerData = ((object)(results[1]));
            @return = ((object)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSAS_ApplyUpdates(string ProviderName, object Delta, int MaxErrors, object OwnerData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SAS_ApplyUpdates", new object[] {
                        ProviderName,
                        Delta,
                        MaxErrors,
                        OwnerData}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSAS_ApplyUpdates(System.IAsyncResult asyncResult, out object OwnerData, out object @return) {
            object[] results = this.EndInvoke(asyncResult);
            OwnerData = ((object)(results[1]));
            @return = ((object)(results[2]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#SAS_GetRecords", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("RecsOut")]
        public int SAS_GetRecords(string ProviderName, int Count, int Options, string CommandText, ref object Params, ref object OwnerData, out object @return) {
            object[] results = this.Invoke("SAS_GetRecords", new object[] {
                        ProviderName,
                        Count,
                        Options,
                        CommandText,
                        Params,
                        OwnerData});
            Params = ((object)(results[1]));
            OwnerData = ((object)(results[2]));
            @return = ((object)(results[3]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSAS_GetRecords(string ProviderName, int Count, int Options, string CommandText, object Params, object OwnerData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SAS_GetRecords", new object[] {
                        ProviderName,
                        Count,
                        Options,
                        CommandText,
                        Params,
                        OwnerData}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSAS_GetRecords(System.IAsyncResult asyncResult, out object Params, out object OwnerData, out object @return) {
            object[] results = this.EndInvoke(asyncResult);
            Params = ((object)(results[1]));
            OwnerData = ((object)(results[2]));
            @return = ((object)(results[3]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#SAS_DataRequest", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object SAS_DataRequest(string ProviderName, object Data) {
            object[] results = this.Invoke("SAS_DataRequest", new object[] {
                        ProviderName,
                        Data});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSAS_DataRequest(string ProviderName, object Data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SAS_DataRequest", new object[] {
                        ProviderName,
                        Data}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndSAS_DataRequest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#SAS_GetProviderNames", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string[] SAS_GetProviderNames() {
            object[] results = this.Invoke("SAS_GetProviderNames", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSAS_GetProviderNames(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SAS_GetProviderNames", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndSAS_GetProviderNames(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#SAS_GetParams", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object SAS_GetParams(string ProviderName, ref object OwnerData) {
            object[] results = this.Invoke("SAS_GetParams", new object[] {
                        ProviderName,
                        OwnerData});
            OwnerData = ((object)(results[1]));
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSAS_GetParams(string ProviderName, object OwnerData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SAS_GetParams", new object[] {
                        ProviderName,
                        OwnerData}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndSAS_GetParams(System.IAsyncResult asyncResult, out object OwnerData) {
            object[] results = this.EndInvoke(asyncResult);
            OwnerData = ((object)(results[1]));
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#SAS_RowRequest", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object SAS_RowRequest(string ProviderName, object Row, int RequestType, ref object OwnerData) {
            object[] results = this.Invoke("SAS_RowRequest", new object[] {
                        ProviderName,
                        Row,
                        RequestType,
                        OwnerData});
            OwnerData = ((object)(results[1]));
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSAS_RowRequest(string ProviderName, object Row, int RequestType, object OwnerData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SAS_RowRequest", new object[] {
                        ProviderName,
                        Row,
                        RequestType,
                        OwnerData}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndSAS_RowRequest(System.IAsyncResult asyncResult, out object OwnerData) {
            object[] results = this.EndInvoke(asyncResult);
            OwnerData = ((object)(results[1]));
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#SAS_Execute", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        public void SAS_Execute(string ProviderName, string CommandText, ref object Params, ref object OwnerData) {
            object[] results = this.Invoke("SAS_Execute", new object[] {
                        ProviderName,
                        CommandText,
                        Params,
                        OwnerData});
            Params = ((object)(results[0]));
            OwnerData = ((object)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSAS_Execute(string ProviderName, string CommandText, object Params, object OwnerData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SAS_Execute", new object[] {
                        ProviderName,
                        CommandText,
                        Params,
                        OwnerData}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSAS_Execute(System.IAsyncResult asyncResult, out object Params, out object OwnerData) {
            object[] results = this.EndInvoke(asyncResult);
            Params = ((object)(results[0]));
            OwnerData = ((object)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#RetCodigoMesa", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string RetCodigoMesa(int codEmpresa, int numMesa) {
            object[] results = this.Invoke("RetCodigoMesa", new object[] {
                        codEmpresa,
                        numMesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetCodigoMesa(int codEmpresa, int numMesa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetCodigoMesa", new object[] {
                        codEmpresa,
                        numMesa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRetCodigoMesa(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#CarregaCategoria", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CarregaCategoria(string codEmpresa) {
            object[] results = this.Invoke("CarregaCategoria", new object[] {
                        codEmpresa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCarregaCategoria(string codEmpresa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CarregaCategoria", new object[] {
                        codEmpresa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCarregaCategoria(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#VerificaCodigoMesa", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string VerificaCodigoMesa(string codMesa, int codEmpresa, int numMesa) {
            object[] results = this.Invoke("VerificaCodigoMesa", new object[] {
                        codMesa,
                        codEmpresa,
                        numMesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginVerificaCodigoMesa(string codMesa, int codEmpresa, int numMesa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VerificaCodigoMesa", new object[] {
                        codMesa,
                        codEmpresa,
                        numMesa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndVerificaCodigoMesa(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#CarregaEmpresa", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CarregaEmpresa() {
            object[] results = this.Invoke("CarregaEmpresa", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCarregaEmpresa(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CarregaEmpresa", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCarregaEmpresa(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#CarregaProduto", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CarregaProduto(string codEmpresa) {
            object[] results = this.Invoke("CarregaProduto", new object[] {
                        codEmpresa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCarregaProduto(string codEmpresa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CarregaProduto", new object[] {
                        codEmpresa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCarregaProduto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#GravaPedido", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GravaPedido(int codPedido, int codEmpresa, int numMesa, string dataPedido, string valorTotal, string numSerial, string numCelular, string dataFechado, string codigoMesa) {
            object[] results = this.Invoke("GravaPedido", new object[] {
                        codPedido,
                        codEmpresa,
                        numMesa,
                        dataPedido,
                        valorTotal,
                        numSerial,
                        numCelular,
                        dataFechado,
                        codigoMesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGravaPedido(int codPedido, int codEmpresa, int numMesa, string dataPedido, string valorTotal, string numSerial, string numCelular, string dataFechado, string codigoMesa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GravaPedido", new object[] {
                        codPedido,
                        codEmpresa,
                        numMesa,
                        dataPedido,
                        valorTotal,
                        numSerial,
                        numCelular,
                        dataFechado,
                        codigoMesa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGravaPedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#GravaPedidoItem", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GravaPedidoItem(int codEmpresa, int codPedido, int itemPedido, int codProduto, string qtde, string precoUnit, string numSerial, string numCelular, string lembrete, string qtdItemEnviado, string codEnvio) {
            object[] results = this.Invoke("GravaPedidoItem", new object[] {
                        codEmpresa,
                        codPedido,
                        itemPedido,
                        codProduto,
                        qtde,
                        precoUnit,
                        numSerial,
                        numCelular,
                        lembrete,
                        qtdItemEnviado,
                        codEnvio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGravaPedidoItem(int codEmpresa, int codPedido, int itemPedido, int codProduto, string qtde, string precoUnit, string numSerial, string numCelular, string lembrete, string qtdItemEnviado, string codEnvio, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GravaPedidoItem", new object[] {
                        codEmpresa,
                        codPedido,
                        itemPedido,
                        codProduto,
                        qtde,
                        precoUnit,
                        numSerial,
                        numCelular,
                        lembrete,
                        qtdItemEnviado,
                        codEnvio}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGravaPedidoItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#RetornaProxCodPedido", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string RetornaProxCodPedido(string codEmpresa) {
            object[] results = this.Invoke("RetornaProxCodPedido", new object[] {
                        codEmpresa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaProxCodPedido(string codEmpresa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaProxCodPedido", new object[] {
                        codEmpresa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRetornaProxCodPedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#AtualizaPedido", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string AtualizaPedido(int codEmpresa, int codPedido, int numMesa, string valorTotal) {
            object[] results = this.Invoke("AtualizaPedido", new object[] {
                        codEmpresa,
                        codPedido,
                        numMesa,
                        valorTotal});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAtualizaPedido(int codEmpresa, int codPedido, int numMesa, string valorTotal, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AtualizaPedido", new object[] {
                        codEmpresa,
                        codPedido,
                        numMesa,
                        valorTotal}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndAtualizaPedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#VerificaPedido", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string VerificaPedido(int codEmpresa, int codPedido, int numMesa) {
            object[] results = this.Invoke("VerificaPedido", new object[] {
                        codEmpresa,
                        codPedido,
                        numMesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginVerificaPedido(int codEmpresa, int codPedido, int numMesa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VerificaPedido", new object[] {
                        codEmpresa,
                        codPedido,
                        numMesa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndVerificaPedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#RetornaSubTotal", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string RetornaSubTotal(int codEmpresa, int numMesa) {
            object[] results = this.Invoke("RetornaSubTotal", new object[] {
                        codEmpresa,
                        numMesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetornaSubTotal(int codEmpresa, int numMesa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RetornaSubTotal", new object[] {
                        codEmpresa,
                        numMesa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRetornaSubTotal(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#Estatistica", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Estatistica(string sProcesso, string sData, int codEmpresa, int sCodMesa) {
            object[] results = this.Invoke("Estatistica", new object[] {
                        sProcesso,
                        sData,
                        codEmpresa,
                        sCodMesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEstatistica(string sProcesso, string sData, int codEmpresa, int sCodMesa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Estatistica", new object[] {
                        sProcesso,
                        sData,
                        codEmpresa,
                        sCodMesa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndEstatistica(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#CarregaMensagem", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CarregaMensagem(string codEmpresa) {
            object[] results = this.Invoke("CarregaMensagem", new object[] {
                        codEmpresa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCarregaMensagem(string codEmpresa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CarregaMensagem", new object[] {
                        codEmpresa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCarregaMensagem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ModuloServer-IdmServer#CarregaStatus", RequestNamespace="urn:ModuloServer-IdmServer", ResponseNamespace="urn:ModuloServer-IdmServer")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CarregaStatus(string codEmpresa) {
            object[] results = this.Invoke("CarregaStatus", new object[] {
                        codEmpresa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCarregaStatus(string codEmpresa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CarregaStatus", new object[] {
                        codEmpresa}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCarregaStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
